### ISSUE TITLE
Running npx audit-age with lower node/npm version than what is defined in engines throws ambiguous error

### ISSUE THREAD

**Issue by bjankord** [jaydenseric/audit-age#2]
I tried running `npx audit-age` in my project recently and received the following error.

```bash
npx audit-age
npx: installed 16 in 3.32s
(node:66889) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot convert undefined or null to object
(node:66889) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I thought it might be a node version issue so I checked the package.json for audit-age and saw the engine for node is listed at >=8.5 and npm >=5.2. I updated to node 8.5.0 and npm 5.3.0 and reran the script and it worked fine.

It would be nice to get a warning when running `npx audit-age` that the current node version is not compatible. Ideally, I think this should be the responsibility of npx, but wanted to let you and others know if they ran into the same issue.

**Comment by jaydenseric** [comment]
Thanks for the suggestion. Node.js v8 is EOL in the next few weeks, so I don't think we should worry to much about people using versions even older than that anymore.

The `package.json` `engines` field is the standard way to declare Node.js support, which we are doing. When I next do some maintenance work on this project I'll add a "Support" section to the readme and mention the Node.js versions that work.
